runtime: python27
service: $SERVICE_NAME
api_version: 1
threadsafe: false

handlers:
- url: .*
  script: redir.app

env_variables:
  REDIR_TO: "$REDIR_TO"

libraries:
- name: webapp2
  version: "2.5.2"
