periodics:
- cron: "43 */2 * * *"
  name: ci-knative-serving-contour-latest-beta-prow-tests
  agent: kubernetes
  decorate: true
  cluster: "build-knative"
  extra_refs:
  - org: knative
    repo: serving
    path_alias: knative.dev/serving
    base_ref: master
  spec:
    containers:
    - image: gcr.io/knative-tests/test-infra/prow-tests:beta
      imagePullPolicy: Always
      command:
      - runner.sh
      args:
      - "./test/presubmit-tests.sh"
      - "--run-test"
      - "./test/e2e-tests.sh --contour-version latest"
      - "--run-test"
      - "./test/e2e-auto-tls-tests.sh --contour-version latest"
      volumeMounts:
      - name: test-account
        mountPath: /etc/test-account
        readOnly: true
      env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/test-account/service-account.json
      - name: E2E_CLUSTER_REGION
        value: us-central1
  volumes:
  - name: test-account
    secret:
      secretName: test-account

