# Automatically configures datasource for grafana on startup. See http://docs.grafana.org/administration/provisioning/#example-datasource-config-file
# config file version
apiVersion: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: psql
  # <string, required> datasource type. Required
  type: postgres
  # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
  access: direct
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: postgres-db-0.postgres-db.default.svc.cluster.local
  # <string> database password, if used
  password: ${PG_PASS}
  # <string> database user, if used
  user: gha_admin
  # <string> database name, if used
  database: knative
  # <map> fields that will be converted to json and stored in jsonData
  jsonData:
     sslmode: "disable"
     graphiteVersion: "1.1"
     tlsAuth: true
     tlsAuthWithCACert: true
  # <string> json object of data that will be encrypted.
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
    user: gha_admin
    password: ${PG_PASS}
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: false
