apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  labels:
    app.kubernetes.io/name: grafana
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  endpoints:
  - port: grafana
    interval: 30s
