apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: https-lb
    namespace: default
  hostnames:
  - grafana.knative.dev
  rules:
  - matches:
    - path:
        value: /
    backendRefs:
    - name: grafana
      port: 80
