apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oauth
#   namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: knative-tests
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      engineVersion: v2
      data:
        client_id: '{{ printf "{{ .grafana_client_id }}" }}'
        client_secret: '{{ printf "{{ .grafana_client_secret }}" }}'
  data:
  - secretKey: grafana_client_id
    remoteRef:
      key: github-credentials
      property: grafana_client_id
  - secretKey: grafana_client_secret
    remoteRef:
      key: github-credentials
      property: grafana_client_secret
