---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: perf-tests
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
      - envFrom:
        - secretRef:
            name: grafana-creds
        env:
        - name: publicDashboards
          value: true
        image: grafana/grafana:9.1.0
        name: grafana
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
            name: http-grafana
            protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /robots.txt
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        volumeMounts:
          - mountPath: /var/lib/grafana/
            name: data-dir
      volumes:
        - name: data-dir
          persistentVolumeClaim:
            claimName: graf-data-dir-pvc
---
apiVersion: v1
kind: Service
  labels:
    app: grafana
  name: grafana
  namespace: perf-tests
spec:
  ports:
  - port: 443
    name: https
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
