---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: perf-tests
  labels:
    app: influxdb
  name: influxdb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
