apiVersion: v1
kind: Namespace
metadata:
  name: perf-tests
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-user
  namespace: perf-tests
subjects:
  - kind: Group
    name: k8s-infra-rbac-perf-tests@knative.dev
roleRef:
  kind: ClusterRole
  name: namespace-user
  apiGroup: rbac.authorization.k8s.io


