# This role will be scoped to namespace when used with RoleBinding
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-user
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"

