org: knative
repo: client
branches: [main]
image: gcr.io/knative-tests/test-infra/prow-tests:v20220428-d4a62c20
imagePullPolicy: Always
cluster: prow-build

jobs:
  - name: build-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --build-tests]
    excluded_requirements: [gcp]

  - name: unit-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --unit-tests]
    excluded_requirements: [gcp]

  - name: integration-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --integration-tests]

  - name: integration-tests-latest-release
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-integration-tests-latest-release.sh]

  - name: continuous
    types: [periodic]
    command: [runner.sh, ./test/presubmit-tests.sh, --all-tests]

  - name: tekton
    types: [periodic]
    command: [runner.sh, ./test/tekton-tests.sh]

  - name: s390x-e2e-tests
    cron: 0 14 * * *
    types: [periodic]
    requirements: [s390x]
    command: [runner.sh]
    args:
      - bash
      - -c
      - |
        mkdir -p /root/.kube
        cat /opt/cluster/ci-script > connect.sh
        chmod +x connect.sh
        ./connect.sh client-main
        kubectl get cm s390x-config-client -n default -o jsonpath='{.data.adjustment-script}' > adjust.sh
        chmod +x adjust.sh
        ./adjust.sh
        ./test/e2e-tests.sh --run-tests
    env:
      - name: INGRESS_CLASS
        value: contour.ingress.networking.knative.dev

  - name: nightly
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release]
    requirements: [nightly]
    excluded_requirements: [gcp]
    reporter_config:
      slack:
        channel: client
        report_template: |
          "The nightly release job fails, check the log: <{{.Status.URL}}|View logs>"
        job_states_to_report:
        - "failure"

  - name: release
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --auto-release, --release-gcs, knative-releases/client, --release-gcr, gcr.io/knative-releases, --github-token, /etc/hub-token/token]
    requirements: [release]
    excluded_requirements: [gcp]

requirement_presets:
  nightly:
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/nightly-account/service-account.json
    volumeMounts:
      - name: nightly-account
        mountPath: /etc/nightly-account
        readOnly: true
    volumes:
      - name: nightly-account
        secret:
          items:
          - key: nightly.json
            path: service-account.json
          secretName: prow-google-credentials

  release:
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/release-account/service-account.json
      - name: E2E_CLUSTER_REGION
        value: us-central1
    volumeMounts:
      - name: hub-token
        mountPath: /etc/hub-token
        readOnly: true
      - name: release-account
        mountPath: /etc/release-account
        readOnly: true
    volumes:
      - name: hub-token
        secret:
          items:
          - key: hub_token
            path: token
          secretName: github-credentials
      - name: release-account
        secret:
          items:
          - key: release.json
            path: service-account.json
          secretName: prow-google-credentials

  gcp:
    env:
      - name: E2E_CLUSTER_REGION
        value: us-central1
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/test-account/service-account.json
    volumeMounts:
      - name: test-account
        mountPath: /etc/test-account
        readOnly: true
    volumes:
      - name: test-account
        secret:
          items:
          - key: service-account-key.json
            path: service-account.json
          secretName: prow-google-credentials
