org: knative
repo: eventing
branches: [main]
image: gcr.io/knative-tests/test-infra/prow-tests:v20230126-0d51bee0

jobs:
  - name: build-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --build-tests]
    excluded_requirements: [gcp]

  - name: unit-tests
    types: [presubmit]
    resources: default
    command: [runner.sh, ./test/presubmit-tests.sh, --unit-tests]
    excluded_requirements: [gcp]

  - name: conformance-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, ./test/e2e-conformance-tests.sh]

  - name: reconciler-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, ./test/e2e-rekt-tests.sh]

  - name: upgrade-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, ./test/e2e-upgrade-tests.sh]

  - name: continuous
    types: [periodic]
    timeout: 3h
    command: [runner.sh, ./test/presubmit-tests.sh, --all-tests]

  - name: s390x-e2e-tests
    cron: 20 4 * * *
    types: [periodic]
    requirements: [s390x]
    command: [runner.sh]
    args:
      - bash
      - -c
      - |
        mkdir -p /root/.kube
        cat /opt/cluster/ci-script > connect.sh
        chmod +x connect.sh
        ./connect.sh eventing-main
        kubectl get cm s390x-config-eventing -n default -o jsonpath='{.data.adjustment-script}' > adjust.sh
        chmod +x adjust.sh
        ./adjust.sh
        ./test/e2e-tests.sh --run-tests
    env:
      - name: SYSTEM_NAMESPACE
        value: knative-eventing
      - name: SCALE_CHAOSDUCK_TO_ZERO
        value: "1"

  - name: s390x-e2e-reconciler-tests
    cron: 20 5 * * *
    types: [periodic]
    requirements: [s390x]
    command: [runner.sh]
    args:
      - bash
      - -c
      - |
        mkdir -p /root/.kube
        cat /opt/cluster/ci-script > connect.sh
        chmod +x connect.sh
        ./connect.sh eventing_rekt-main
        kubectl get cm s390x-config-eventing -n default -o jsonpath='{.data.adjustment-script}' > adjust.sh
        chmod +x adjust.sh
        ./adjust.sh
        ./test/e2e-rekt-tests.sh --run-tests
    env:
      - name: SYSTEM_NAMESPACE
        value: knative-eventing
      - name: SCALE_CHAOSDUCK_TO_ZERO
        value: "1"

  - name: ppc64le-e2e-tests
    cron: 0 7 * * *
    types: [periodic]
    requirements: [ppc64le]
    command: [runner.sh]
    args:
      - bash
      - -c
      - |
        cat /opt/cluster/ci-script > /tmp/connect.sh
        chmod +x /tmp/connect.sh
        . /tmp/connect.sh ${CI_JOB}
        ./test/e2e-tests.sh --run-tests
    env:
      - name: SYSTEM_NAMESPACE
        value: knative-eventing
      - name: SCALE_CHAOSDUCK_TO_ZERO
        value: "1"
      - name: CI_JOB
        value: "eventing-main"

  - name: ppc64le-e2e-reconciler-tests
    cron: 30 4 * * *
    types: [periodic]
    requirements: [ppc64le]
    command: [runner.sh]
    args:
      - bash
      - -c
      - |
        cat /opt/cluster/ci-script > /tmp/connect.sh
        chmod +x /tmp/connect.sh
        . /tmp/connect.sh ${CI_JOB}
        ./test/e2e-rekt-tests.sh --run-tests
    env:
      - name: SYSTEM_NAMESPACE
        value: knative-eventing
      - name: SCALE_CHAOSDUCK_TO_ZERO
        value: "1"
      - name: CI_JOB
        value: "eventing_rekt-main"

  - name: nightly
    types: [periodic]
    timeout: 4h
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release]
    requirements: [nightly]
    excluded_requirements: [gcp]
    max_concurrency: 1
    reporter_config:
      slack:
        channel: eventing
        report_template: |
          "The nightly release has failed, please check the logs: <{{.Status.URL}}|View logs>"
        job_states_to_report:
        - "failure"

  - name: release
    types: [periodic]
    timeout: 4h
    command: [runner.sh, ./hack/release.sh, --auto-release, --release-gcs, knative-releases/eventing, --release-gcr, gcr.io/knative-releases, --github-token, /etc/hub-token/token]
    requirements: [release]
    excluded_requirements: [gcp]
    max_concurrency: 1

resources: high
resources_presets:
  high:
    limits:
      memory: 16Gi
    requests:
      memory: 12Gi

  default:
    limits:
      memory: 10Gi
    requests:
      memory: 8Gi
