org: knative
repo: func
branches: [main]
image: gcr.io/knative-tests/test-infra/prow-tests:v20221013-fb4b58b9

jobs:
  - name: nightly
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release,
      --apple-codesign-key, /etc/notary/cert.p12,
      --apple-notary-api-key, /etc/notary/key.json,
      --apple-codesign-password-file, /etc/notary/password]
    requirements: [nightly-notary, docker]
    excluded_requirements: [gcp]
    max_concurrency: 1
    reporter_config:
      slack:
        channel: functions
        report_template: |
          "The nightly release has failed, please check the logs: <{{.Status.URL}}|View logs>"
        job_states_to_report:
        - "failure"

  - name: release
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --auto-release, --release-gcs, knative-releases/func, --release-gcr, gcr.io/knative-releases, --github-token, /etc/hub-token/token,
      --apple-codesign-key, /etc/notary/cert.p12,
      --apple-notary-api-key, /etc/notary/key.json,
      --apple-codesign-password-file, /etc/notary/password]
    requirements: [release-notary, docker]
    max_concurrency: 1
    excluded_requirements: [gcp]
