org: knative
repo: operator
branches: [main]
image: gcr.io/knative-tests/test-infra/prow-tests:v20220714-5fb3ba3d
imagePullPolicy: Always

jobs:
  - name: build-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --build-tests]
    excluded_requirements: [gcp]

  - name: unit-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --unit-tests]
    excluded_requirements: [gcp]

  - name: integration-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --integration-tests]

  - name: upgrade-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, ./test/e2e-upgrade-tests.sh]

  - name: serving-upgrade-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, ./test/e2e-serving-upgrade-tests.sh]

  - name: eventing-upgrade-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --run-test, ./test/e2e-eventing-upgrade-tests.sh]

  - name: continuous
    types: [periodic]
    command: [runner.sh, ./test/presubmit-tests.sh, --all-tests]

  - name: s390x-e2e-tests
    cron: 0 13 * * *
    types: [periodic]
    requirements: [s390x]
    command: [runner.sh]
    args:
      - bash
      - -c
      - |
        mkdir -p /root/.kube
        cat /opt/cluster/ci-script > connect.sh
        chmod +x connect.sh
        ./connect.sh operator-main
        kubectl get cm s390x-config-operator -n default -o jsonpath='{.data.adjustment-script}' > adjust.sh
        chmod +x adjust.sh
        ./adjust.sh
        ./test/e2e-tests.sh --run-tests
    env:
      - name: INGRESS_CLASS
        value: contour.ingress.networking.knative.dev

  - name: ppc64le-e2e-tests
    cron: 0 13 * * *
    types: [periodic]
    requirements: [ppc64le]
    command: [runner.sh]
    args:
      - bash
      - -c
      - |
        cat /opt/cluster/ci-script > /tmp/connect.sh
        chmod +x /tmp/connect.sh
        . /tmp/connect.sh ${CI_JOB}
        ./test/e2e-tests.sh --run-tests
    env:
      - name: CI_JOB
        value: "operator-main"
      - name: INGRESS_CLASS
        value: contour.ingress.networking.knative.dev

  - name: nightly
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release]
    requirements: [nightly]
    excluded_requirements: [gcp]
    reporter_config:
      slack:
        channel: operator
        report_template: |
          "The nightly release job fails, check the log: <{{.Status.URL}}|View logs>"
        job_states_to_report:
        - "failure"

  - name: release
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --auto-release, --release-gcs, knative-releases/operator, --release-gcr, gcr.io/knative-releases, --github-token, /etc/hub-token/token]
    requirements: [release]
    excluded_requirements: [gcp]
