cluster: prow-build

requirement_presets:
  release:
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/release-account/service-account.json
      - name: E2E_CLUSTER_REGION
        value: us-central1
      # ORG_NAME must be set to knative-sandbox, overwriting the preset in root .base.yaml
      - name: ORG_NAME
        value: knative-sandbox
      - name: ATTEST_IMAGES
        value: "true"
    volumeMounts:
      - name: hub-token
        mountPath: /etc/hub-token
        readOnly: true
      - name: release-account
        mountPath: /etc/release-account
        readOnly: true
    volumes:
      - name: hub-token
        secret:
          items:
          - key: hub_token
            path: token
          secretName: github-credentials
      - name: release-account
        secret:
          items:
          - key: release.json
            path: service-account.json
          secretName: prow-google-credentials

  release-notary: # this preset is for knative projects that release binaries ONLY.
    podSpec:
      serviceAccountName: release
    env:
      - name: E2E_CLUSTER_REGION
        value: us-central1
      - name: SIGN_IMAGES
        value: "true"
     # ORG_NAME must be set to knative-sandbox, overwriting the preset in root .base.yaml
      - name: ORG_NAME
        value: knative-sandbox
      - name: ATTEST_IMAGES
        value: "true"
    volumeMounts:
      - name: hub-token
        mountPath: /etc/hub-token
        readOnly: true
      - name: apple-notary-creds
        mountPath: /etc/notary
        readOnly: true
    volumes:
      - name: hub-token
        secret:
          items:
          - key: hub_token
            path: token
          secretName: github-credentials
      - name: apple-notary-creds
        secret:
          items:
          - key: notary-api-key
            path: key.json
          - key: signing-certificate
            path: cert.p12
          - key: signing-certificate-password
            path: password
          secretName: apple-notary-creds
