org: knative-sandbox
repo: eventing-gitlab
branches: [main]
image: gcr.io/knative-tests/test-infra/prow-tests:v20221005-aef947d7

jobs:
  - name: continuous
    types: [periodic]
    command: [runner.sh, ./test/presubmit-tests.sh, --all-tests]
    requirements: [docker]

  - name: nightly
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release]
    requirements: [nightly, docker]
    excluded_requirements: [gcp]

  - name: release
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --auto-release, --release-gcs, knative-releases/eventing-gitlab, --release-gcr, gcr.io/knative-releases, --github-token, /etc/hub-token/token]
    requirements: [release, docker]
    excluded_requirements: [gcp]

resources_presets:
  default:
    limits:
      memory: 16Gi
    requests:
      memory: 12Gi
