org: knative-sandbox
repo: eventing-istio
branches: [main]
image: gcr.io/knative-tests/test-infra/prow-tests:v20230220-8e42b241

jobs:
  - name: build-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --build-tests]
    excluded_requirements: [gcp]

  - name: unit-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --unit-tests]
    excluded_requirements: [gcp]

  - name: integration-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --integration-tests]
    requirements: [docker]

  - name: continuous
    types: [periodic]
    command: [runner.sh, ./test/presubmit-tests.sh, --all-tests]
    requirements: [docker]

  - name: nightly
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release]
    requirements: [nightly, docker]
    excluded_requirements: [gcp]
    max_concurrency: 1
    reporter_config:
      slack:
        channel: knative-eventing
        report_template: |
          "The nightly release job fails, check the log: <{{.Status.URL}}|View logs>"
        job_states_to_report:
        - "failure"

  - name: release
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --auto-release, --release-gcs, knative-releases/eventing-istio, --release-gcr, gcr.io/knative-releases, --github-token, /etc/hub-token/token]
    requirements: [release, docker]
    excluded_requirements: [gcp]
    max_concurrency: 1
