org: knative-sandbox
repo: eventing-natss
branches: [main]
image: us-docker.pkg.dev/knative-tests/images/prow-tests:v20230605-5de90de6

jobs:
  - name: continuous
    types: [periodic]
    command: [runner.sh, ./test/presubmit-tests.sh, --all-tests]

  - name: nightly
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release]
    requirements: [nightly]
    excluded_requirements: [gcp]
    max_concurrency: 1
    reporter_config:
      slack:
        channel: knative-eventing
        job_states_to_report:
        - failure
        report_template: |
          "The nightly release job for eventing-natss has failed, please check the log: <{{.Status.URL}}|View logs>"

  - name: release
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --auto-release, --release-gcs, knative-releases/eventing-natss, --release-gcr, gcr.io/knative-releases, --github-token, /etc/hub-token/token]
    requirements: [release]
    excluded_requirements: [gcp]
    max_concurrency: 1
