org: knative-sandbox
repo: kn-plugin-service-log
branches: [main]
image: gcr.io/knative-tests/test-infra/prow-tests:v20220412-eae25a77
imagePullPolicy: Always

jobs:
  - name: build-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --build-tests]
    excluded_requirements: [gcp]

  - name: unit-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --unit-tests]
    excluded_requirements: [gcp]

  - name: integration-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --integration-tests]

  - name: continuous
    types: [periodic]
    command: [runner.sh, ./test/presubmit-tests.sh, --all-tests]

  - name: nightly
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release]
    requirements: [nightly, docker]
    excluded_requirements: [gcp]

  - name: release
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --auto-release, --release-gcs, knative-releases/kn-plugin-service-log, --release-gcr, gcr.io/knative-releases, --github-token, /etc/hub-token/token]
    requirements: [release, docker]
    excluded_requirements: [gcp]
