org: knative-sandbox
repo: kn-plugin-event
branches: [main]
image: gcr.io/knative-tests/test-infra/prow-tests:v20230410-37f7de8a

jobs:
  - name: build-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --build-tests]
    excluded_requirements: [gcp]

  - name: unit-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --unit-tests]
    excluded_requirements: [gcp]

  - name: integration-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --integration-tests]

  - name: continuous
    types: [periodic]
    command: [runner.sh, ./test/presubmit-tests.sh, --all-tests]
  - name: s390x-e2e-tests
    cron: 20 10 * * *
    types: [periodic]
    requirements: [s390x]
    command: [runner.sh]
    args:
      - bash
      - -c
      - |
        mkdir -p /root/.kube
        cat /opt/cluster/ci-script > connect.sh
        chmod +x connect.sh
        ./connect.sh plugin_event-main
        kubectl get cm s390x-config-plugin-event -n default -o jsonpath='{.data.adjustment-script}' > adjust.sh
        chmod +x adjust.sh
        ./adjust.sh
        ./test/e2e-tests.sh --run-tests
    excluded_requirements:
    - gcp
  - name: nightly
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release,
      --apple-codesign-key, /etc/notary/cert.p12,
      --apple-notary-api-key, /etc/notary/key.json,
      --apple-codesign-password-file, /etc/notary/password]
    requirements: [nightly-notary]
    excluded_requirements: [gcp]
    max_concurrency: 1

  - name: release
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --auto-release, --release-gcs, knative-releases/kn-plugin-event, --release-gcr, gcr.io/knative-releases, --github-token, /etc/hub-token/token,
      --apple-codesign-key, /etc/notary/cert.p12,
      --apple-notary-api-key, /etc/notary/key.json,
      --apple-codesign-password-file, /etc/notary/password]
    requirements: [release-notary]
    excluded_requirements: [gcp]
    max_concurrency: 1
