org: knative-sandbox
repo: net-http01
branches: [main]
image: gcr.io/knative-tests/test-infra/prow-tests:v20230413-35d401a2

jobs:
  - name: build-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --build-tests]
    excluded_requirements: [gcp]

  - name: unit-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --unit-tests]
    excluded_requirements: [gcp]

  - name: integration-tests
    types: [presubmit]
    command: [runner.sh, ./test/presubmit-tests.sh, --integration-tests]

  - name: continuous
    types: [periodic]
    command: [runner.sh, ./test/presubmit-tests.sh, --all-tests]

  - name: nightly
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --publish, --tag-release]
    requirements: [nightly]
    max_concurrency: 1
    excluded_requirements: [gcp]
    reporter_config:
      slack:
        channel: knative-serving-bots
        report_template: |
          "[net-http01] nightly release job fails, check the log: <{{.Status.URL}}|View logs>"
        job_states_to_report:
        - "failure"

  - name: release
    types: [periodic]
    command: [runner.sh, ./hack/release.sh, --auto-release, --release-gcs, knative-releases/net-http01, --release-gcr, gcr.io/knative-releases, --github-token, /etc/hub-token/token]
    requirements: [release]
    excluded_requirements: [gcp]
    max_concurrency: 1
