apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: default
spec:
  clusterIP: "None"
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: postgres-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: default
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  serviceName: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pass
              key: pg_postgres_password
        - name: POSTGRES_DB
          value: "postgres"
        - name: PGDATA
          value: "/mount/data/postgresql"
        image: gcr.io/knative-tests/devstats-postgres:latest
        imagePullPolicy: Always
        command: ["/usr/local/bin/postgre-docker-entrypoint.sh", "postgres",]
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: "/mount/data"
          name: "nfs"
      volumes:
      - name: "nfs"
        persistentVolumeClaim:
          claimName: "devstats-claim"

