{
 "title": "Boskos Server Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(boskos_http_request_duration_seconds_bucket, instance)"
   },
   {
    "name": "path",
    "label": "path",
    "query": "label_values(boskos_http_request_duration_seconds_bucket, path)"
   },
   {
    "name": "status",
    "label": "status",
    "query": "label_values(boskos_http_request_duration_seconds_bucket, status)"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency distribution for instance ${instance} path ${path} and status ${status}",
   "type": "graph",
   "description": "histogram_quantile(phi, sum(rate(boskos_http_request_duration_seconds_bucket[5m])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(boskos_http_request_duration_seconds_bucket{path=~\"${path}\", status=~\"${status}\", instance=~\"${instance}\"}[5m])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(boskos_http_request_duration_seconds_bucket{path=~\"${path}\", status=~\"${status}\", instance=~\"${instance}\"}[5m])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(boskos_http_request_duration_seconds_bucket{path=~\"${path}\", status=~\"${status}\", instance=~\"${instance}\"}[5m])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "Request rate for instance ${instance}",
   "type": "graph",
   "description": "sum(rate(boskos_http_request_duration_seconds_count{instance=~\"${instance}\"}[5m])) by (path, status)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(boskos_http_request_duration_seconds_count{instance=~\"${instance}\"}[5m])) by (path, status)",
     "legendFormat": "{{path}} {{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Boskos Resource Usage",
 "time": { "from": "now-1d", "to": "now" },
 "panels": [
  {
   "title": "GKE projects usage status",
   "type": "graph",
   "description": "The number of GKE projectss in each state.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"gke-project\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}
{
 "title": "deck dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "path",
    "label": "path",
    "query": "label_values(deck_http_request_duration_seconds_count{job=\"deck\"}, path)"
   },
   {
    "name": "method",
    "label": "method",
    "query": "label_values(deck_http_request_duration_seconds_count{job=\"deck\"}, method)"
   },
   {
    "name": "status",
    "label": "status",
    "query": "label_values(deck_http_request_duration_seconds_count{job=\"deck\"}, status)"
   }
  ]
 },
 "panels": [
  {
   "title": "median latency with (pre-defined) paths, method ${method}, and status ${status}",
   "type": "graph",
   "description": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"<path>\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/tide\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/tide"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/plugin-help.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/plugin-help.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/data.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/data.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/prowjobs.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/prowjobs.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/pr-data.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/pr-data.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/log\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/log"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/rerun\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/rerun"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/spyglass/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/spyglass/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/view/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/view/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/job-history/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/job-history/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/pr-history/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/pr-history/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{path=\"others\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "others"
    }
   ]
  },
  {
   "title": "latency percentile with path ${path}, method ${method}, and status ${status}",
   "type": "graph",
   "description": "histogram_quantile(<phi>, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "traffic: couter by status with path ${path} and method ${method}",
   "type": "graph",
   "description": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m])) by (status)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "status percentage with path ${path} and method ${method}",
   "type": "graph",
   "description": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", status=~\"n..\", path=~\"$path\", method=~\"$method\"}[5m]))/sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\"}[5m]))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", status=~\"2..\", path=~\"$path\", method=~\"$method\"}[5m]))/sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", status=~\"3..\", path=~\"$path\", method=~\"$method\"}[5m]))/sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", status=~\"4..\", path=~\"$path\", method=~\"$method\"}[5m]))/sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", status=~\"5..\", path=~\"$path\", method=~\"$method\"}[5m]))/sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "apdex score with target 2.5s and tolerance 10s, path ${path}, method ${method}, and status ${status}",
   "type": "graph",
   "description": "( sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", le=\"2.5\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job) + sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", le=\"10\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job) ) / 2 / sum(rate(deck_http_request_duration_seconds_count{path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "( sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", le=\"2.5\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job) + sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", le=\"10\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job) ) / 2 / sum(rate(deck_http_request_duration_seconds_count{path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job)"
    }
   ]
  },
  {
   "title": "median response size with (pre-defined) paths, method ${method}, and status ${status}",
   "type": "graph",
   "description": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"<path>\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/tide\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/tide"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/plugin-help.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/plugin-help.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/data.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/data.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/prowjobs.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/prowjobs.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/pr-data.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/pr-data.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/log\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/log"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/rerun\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/rerun"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/spyglass/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/spyglass/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/view/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/view/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/job-history/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/job-history/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/pr-history/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/pr-history/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{path=\"others\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "others"
    }
   ]
  }
 ]
}
{
 "title": "GitHub Cache",
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "login",
    "label": "login",
    "query": "label_values(github_user_info{login=\"knative-prow-robot\"}, login)"
   },
   {
    "name": "path",
    "label": "path",
    "query": "label_values(github_request_duration_count, path)"
   },
   {
    "name": "status",
    "label": "status",
    "query": "label_values(github_request_duration_count, status)"
   },
   {
    "name": "user_agent",
    "label": "user_agent",
    "query": "label_values(github_request_duration_count, user_agent)"
   },
   { "name": "range", "label": "range", "query": "3h,1h,30m,15m,10m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Cache Requests (per hour)",
   "type": "graph",
   "description": "Count of cache requests of each cache mode over the last hour.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses[1h]) * on(token_hash) group_left(login) max(github_user_info{login=\"knative-prow-robot\"}) by (token_hash, login)) by (mode)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=\"knative-prow-robot\"}) by (token_hash, login))",
     "legendFormat": "(No Cost)"
    }
   ]
  },
  {
   "title": "Cache Efficiency",
   "type": "graph",
   "description": "Percentage of cacheable requests that are fulfilled for free.\nNo cost modes are \"COALESCED\" and \"REVALIDATED\".\nCacheable modes include the no cost modes, \"CHANGED\" and \"MISS\".",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=\"knative-prow-robot\"}) by (token_hash, login)) \n/ sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED|MISS|CHANGED\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=\"knative-prow-robot\"}) by (token_hash, login))",
     "legendFormat": "Efficiency"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(ghcache_disk_used) without (instance,pod)",
     "legendFormat": "GB Used"
    },
    {
     "expr": "avg(ghcache_disk_free) without (instance,pod)",
     "legendFormat": "GB Free"
    }
   ]
  },
  {
   "title": "API Tokens Saved: Last hour",
   "type": "singlestat",
   "description": "The number of no cost requests in the last hour.\nThis includes both \"COALESCED\" and \"REVALIDATED\" modes.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=\"knative-prow-robot\"}) by (token_hash, login))"
    }
   ]
  },
  {
   "title": "API Tokens Saved: Last 7 days",
   "type": "singlestat",
   "description": "The number of no cost requests in the last 7 days.\nThis includes both \"COALESCED\" and \"REVALIDATED\" modes.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[7d]) * on(token_hash) group_left(login) max(github_user_info{login=\"knative-prow-robot\"}) by (token_hash, login))"
    }
   ]
  },
  {
   "title": "Token Usage",
   "type": "graph",
   "description": "GitHub token usage by login and API version.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(github_token_usage * on(token_hash) group_left(login) max(github_user_info{login=\"knative-prow-robot\"}) by (token_hash, login)) by (api_version, login)",
     "legendFormat": "{{login}} : {{api_version}}"
    }
   ]
  },
  {
   "title": "Request Rates: Overview by status with ${range}",
   "type": "graph",
   "description": "GitHub request rates by status.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_request_duration_count[${range}]) * on(token_hash) group_left(login) max(github_user_info{login=\"knative-prow-robot\"}) by (token_hash, login)) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Rates: Overview by path for ${status} with ${range}",
   "type": "graph",
   "description": "GitHub request rates by path.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_request_duration_count{status=\"${status}\"}[${range}]) * on(token_hash) group_left(login) max(github_user_info{login=\"knative-prow-robot\"}) by (token_hash, login)) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Rates: ${login}, ${path}, and ${status} with ${range}",
   "type": "graph",
   "description": "GitHub request rates by login, path and status.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_request_duration_count{path=\"${path}\", status=\"${status}\"}[${range}]) * on(token_hash) group_left(login) max(github_user_info{login=~\"${login}\"}) by (token_hash, login)) by (login, path, status)",
     "legendFormat": "{{status}}:{{login}}:{{path}}"
    }
   ]
  },
  {
   "title": "Latency Distribution Overview with ${range}",
   "type": "graph",
   "description": "histogram_quantile(<phi>, sum(rate(github_request_duration_bucket[${range}])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(github_request_duration_bucket[5m])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(github_request_duration_bucket[5m])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(github_request_duration_bucket[5m])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "Latency Distribution for ${login}, ${path}, and ${status} with ${range}",
   "type": "graph",
   "description": "histogram_quantile(<phi>, sum(rate(github_request_duration_bucket{path=~\"${path}\", status=~\"${status}\"}[${range}])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(github_request_duration_bucket{path=\"${path}\", status=\"${status}\"}[5m]) * on(token_hash) group_left(login) max(github_user_info{login=~\"${login}\"}) by (token_hash, login)) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(github_request_duration_bucket{path=\"${path}\", status=\"${status}\"}[5m]) * on(token_hash) group_left(login) max(github_user_info{login=~\"${login}\"}) by (token_hash, login)) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(github_request_duration_bucket{path=\"${path}\", status=\"${status}\"}[5m]) * on(token_hash) group_left(login) max(github_user_info{login=~\"${login}\"}) by (token_hash, login)) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "Token Consumption by User Agent",
   "type": "graph",
   "description": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\"}[1h])) by (user_agent)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=\"knative-prow-robot\"}) by (token_hash, login)) by (user_agent)",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "Token Consumption by Path",
   "type": "graph",
   "description": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\"}[1h])) by (path)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=\"knative-prow-robot\"}) by (token_hash, login)) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Token Consumption For Path ${path} by User Agent",
   "type": "graph",
   "description": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\",path=\"${path}\"}[1h])) by (user_agent)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\",path=\"${path}\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=\"knative-prow-robot\"}) by (token_hash, login)) by (user_agent)",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "Token Consumption for User Agent ${user_agent} by Path",
   "type": "graph",
   "description": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\",user_agent=\"${user_agent}\"}[1h])) by (path)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"MISS|NO-STORE|CHANGED\",user_agent=\"${user_agent}\"}[1h]) * on(token_hash) group_left(login) max(github_user_info{login=\"knative-prow-robot\"}) by (token_hash, login)) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}
{
 "title": "hook dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "webhook counter",
   "type": "singlestat",
   "description": "sum(prow_webhook_counter)",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(prow_webhook_counter)" }
   ]
  },
  {
   "title": "webhook response codes",
   "type": "singlestat",
   "description": "sum(prow_webhook_response_codes)",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prow_webhook_response_codes)"
    }
   ]
  },
  {
   "title": "incoming webhooks by event type",
   "type": "graph",
   "description": "sum(rate(prow_webhook_counter[1m])) by (event_type)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prow_webhook_counter[1m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "webhook response codes",
   "type": "graph",
   "description": "sum(rate(prow_webhook_response_codes[1m])) by (response_code)",
   "gridPos": { "h": 9, "w": 24, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prow_webhook_response_codes[1m])) by (response_code)",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "configmap capacities",
   "type": "graph",
   "description": "prow_configmap_size_bytes / 1048576",
   "gridPos": { "h": 9, "w": 24, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "prow_configmap_size_bytes / 1048576",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  }
 ]
}
{
 "title": "plank dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(prowjobs{job=~\"plank|prow-controller-manager\"}, cluster)"
   },
   {
    "name": "org",
    "label": "org",
    "query": "label_values(prowjobs{job=~\"plank|prow-controller-manager\"}, org)"
   },
   {
    "name": "repo",
    "label": "repo",
    "query": "label_values(prowjobs{job=~\"plank|prow-controller-manager\"}, repo)"
   },
   {
    "name": "state",
    "label": "state",
    "query": "all,aborted,error,failure,pending,success,triggered"
   },
   {
    "name": "type",
    "label": "type",
    "query": "all,batch,periodic,presubmit,postsubmit"
   },
   { "name": "group_by_1", "label": "group_by_1", "query": "cluster,org,repo,state,type" },
   { "name": "group_by_2", "label": "group_by_2", "query": "cluster,org,repo,state,type" },
   { "name": "group_by_3", "label": "group_by_3", "query": "cluster,org,repo,state,type" }
  ]
 },
 "panels": [
  {
   "title": "number of Prow jobs by ${group_by_1}",
   "type": "graph",
   "description": "sum(prowjobs{...}) by (${group_by_1})",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prowjobs{job=~\"plank|prow-controller-manager\",cluster=~\"${cluster}\",org=~\"${org}\",repo=~\"${repo}\",state=~\"${state}\",type=~\"${type}\"}) by (${group_by_1})",
     "legendFormat": "{{${group_by_1}}}"
    }
   ]
  },
  {
   "title": "number of Prow jobs by ${group_by_2}",
   "type": "graph",
   "description": "sum(prowjobs{...}) by (${group_by_2})",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prowjobs{job=~\"plank|prow-controller-manager\",cluster=~\"${cluster}\",org=~\"${org}\",repo=~\"${repo}\",state=~\"${state}\",type=~\"${type}\"}) by (${group_by_2})",
     "legendFormat": "{{${group_by_2}}}"
    }
   ]
  },
  {
   "title": "number of Prow jobs by ${group_by_3}",
   "type": "graph",
   "description": "sum(prowjobs{...}) by (${group_by_3})",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prowjobs{job=~\"plank|prow-controller-manager\",cluster=~\"${cluster}\",org=~\"${org}\",repo=~\"${repo}\",state=~\"${state}\",type=~\"${type}\"}) by (${group_by_3})",
     "legendFormat": "{{${group_by_3}}}"
    }
   ]
  }
 ]
}
{
 "title": "prow dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "panels": [
  {
   "title": "up",
   "type": "graph",
   "description": "sum by(job) (up)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum by(job) (up)", "legendFormat": "{{job}}" }
   ]
  }
 ]
}
{
 "title": "sinker dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "time used in each sinker cleaning",
   "type": "graph",
   "description": "sum(sinker_loop_duration_seconds)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sinker_loop_duration_seconds)"
    }
   ]
  },
  {
   "title": "existing pods/prow jobs",
   "type": "graph",
   "description": "sum(sinker_pods_existing) and sum(sinker_prow_jobs_existing)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(sinker_pods_existing)" },
    { "expr": "sum(sinker_prow_jobs_existing)" }
   ]
  },
  {
   "title": "removed pods",
   "type": "graph",
   "description": "sum(sinker_pods_removed) by (reason)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sinker_pods_removed) by (reason)"
    }
   ]
  },
  {
   "title": "cleaned prow jobs",
   "type": "graph",
   "description": "sum(sinker_prow_jobs_cleaned) by (reason)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sinker_prow_jobs_cleaned) by (reason)"
    }
   ]
  },
  {
   "title": "errors occurred in pod cleaning",
   "type": "graph",
   "description": "sum(sinker_pod_removal_errors) by (reason)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sinker_pod_removal_errors) by (reason)"
    }
   ]
  },
  {
   "title": "errors occurred in prow job cleaning",
   "type": "graph",
   "description": "sum(sinker_prow_jobs_cleaning_errors) by (reason)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sinker_prow_jobs_cleaning_errors) by (reason)"
    }
   ]
  }
 ]
}
{
 "title": "SLO Compliance Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Prow overall SLO compliance",
   "type": "graph",
   "description": "slo_prow_ok",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Compliant (T/F)" }
   ],
   "targets": [
    {
     "expr": "label_replace(slo_prow_ok, \"__name__\", \"SLO\", \"\", \"\")"
    }
   ]
  },
  {
   "title": "deck SLO compliance",
   "type": "graph",
   "description": "slo_component_ok{slo=\"deck\"}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Compliant (T/F)" }
   ],
   "targets": [
    {
     "expr": "label_replace(min(slo_component_ok{slo=\"deck\"}) without (slo), \"__name__\", \"SLO\", \"\", \"\")"
    }
   ]
  },
  {
   "title": "hook SLO compliance",
   "type": "graph",
   "description": "slo_component_ok{slo=\"hook\"}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Compliant (T/F)" }
   ],
   "targets": [
    {
     "expr": "label_replace(min(slo_component_ok{slo=\"hook\"}) without (slo), \"__name__\", \"SLO\", \"\", \"\")"
    }
   ]
  },
  {
   "title": "plank SLO compliance",
   "type": "graph",
   "description": "slo_component_ok{slo=\"plank\"}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Compliant (T/F)" }
   ],
   "targets": [
    {
     "expr": "label_replace(min(slo_component_ok{slo=\"plank\"}) without (slo), \"__name__\", \"SLO\", \"\", \"\")"
    }
   ]
  },
  {
   "title": "sinker SLO compliance",
   "type": "graph",
   "description": "slo_component_ok{slo=\"sinker\"}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Compliant (T/F)" }
   ],
   "targets": [
    {
     "expr": "label_replace(min(slo_component_ok{slo=\"sinker\"}) without (slo), \"__name__\", \"SLO\", \"\", \"\")"
    }
   ]
  },
  {
   "title": "tide SLO compliance",
   "type": "graph",
   "description": "slo_component_ok{slo=\"tide\"}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Compliant (T/F)" }
   ],
   "targets": [
    {
     "expr": "label_replace(min(slo_component_ok{slo=\"tide\"}) without (slo), \"__name__\", \"SLO\", \"\", \"\")"
    }
   ]
  },
  {
   "title": "monitoring SLO compliance",
   "type": "graph",
   "description": "slo_component_ok{slo=\"monitoring\"}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Compliant (T/F)" }
   ],
   "targets": [
    {
     "expr": "label_replace(min(slo_component_ok{slo=\"monitoring\"}) without (slo), \"__name__\", \"SLO\", \"\", \"\")"
    }
   ]
  }
 ]
}
{
 "title": "tide dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Tide Pool Sizes",
   "type": "graph",
   "description": "The number of PRs eligible for merge in each Tide pool.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(pooledprs and ((time() - updatetime) < 240)) by (org, repo, branch)",
     "legendFormat": "{{org}}/{{repo}}:{{branch}}"
    }
   ]
  },
  {
   "title": "Tide Daily Merge Rate",
   "type": "graph",
   "description": "Calculated on a 24 hour interval.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(merges_sum[1d]) > 0) by (org, repo, branch)) * 86400",
     "legendFormat": "{{org}}/{{repo}}:{{branch}}"
    }
   ]
  },
  {
   "title": "Tide Daily Merge Rate: Batches Only",
   "type": "graph",
   "description": "Calculated on a 24 hour interval.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(    rate(merges_sum[1d]) - (sum(rate(merges_bucket{le=\"1\"}[1d])) without (le)) > 0     ) by (org, repo, branch)) * 86400",
     "legendFormat": "{{org}}/{{repo}}:{{branch}}"
    }
   ]
  },
  {
   "title": "Tide Pool Sync Errors",
   "type": "graph",
   "description": "Rate of sync errors over a 10m window for each Tide pool.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tidepoolerrors[10m])) by (org, repo, branch)",
     "legendFormat": "{{org}}/{{repo}}:{{branch}}"
    }
   ]
  },
  {
   "title": "Tide Processing Time (seconds)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(syncdur and (changes(syncdur[10m]) > 0))",
     "legendFormat": "Sync time"
    },
    {
     "expr": "max(statusupdatedur and (changes(statusupdatedur[10m]) > 0))",
     "legendFormat": "Status update time"
    }
   ]
  }
 ]
}