gitHubLogin: "knative-prow-updater-robot"
gitHubToken: "/etc/prow-auto-bumper-github-token/token"
skipPullRequest: false
gitHubOrg: "knative"
gitHubRepo: "test-infra"
remoteName: "test-infra"
headBranchName: "autobump-knative"
upstreamURLBase: "https://raw.githubusercontent.com/kubernetes/test-infra/master"
includedConfigPaths:
  - "config/prod/prow/jobs"
extraFiles:
  - "config/prow_common.mk"
  - "config/prod/prow/check_config.sh"
  - "config/prod/prow/run_job.sh"
  - "config/prod/prow/update_config.sh"
targetVersion: "upstream"
prefixes:
  - name: "Prow"
    prefix: "gcr.io/k8s-prow/"
    repo: "https://github.com/kubernetes/test-infra"
    refConfigFile: "config/prow/cluster/deck_deployment.yaml"
    summarise: false
    consistentImages: true
