apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: prow-monitoring
stringData:
  prometheus-additional.yaml: |
    - job_name: knative-prow-builds-boskos
      metrics_path: /metrics
      static_configs:
        - targets:
            - "35.184.198.223:9090"  # external ip boskos-metrics in knative-prow-build-cluster cluster
    - job_name: blackbox
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          # ATTENTION: Keep this in sync with the list in mixins/prometheus/lib/config.libsonnet
          - https://prow.knative.dev
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-prober
type: Opaque
