# Copyright 2020 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

periodics:
- cron: "15 9 * * *"
  name: ci-knative-backup-artifacts
  agent: kubernetes
  decorate: true
  cluster: "build-knative"
  spec:
    containers:
    - image: gcr.io/knative-tests/test-infra/backups:latest
      imagePullPolicy: Always
      command:
      - "/backup.sh"
      args:
      - "/etc/backup-account/service-account.json"
      volumeMounts:
      - name: backup-account
        mountPath: /etc/backup-account
        readOnly: true
    volumes:
    - name: backup-account
      secret:
        secretName: backup-account
- cron: "0 19 * * 1,3,5"
  name: ci-knative-cleanup
  labels:
    prow.k8s.io/pubsub.project: knative-tests
    prow.k8s.io/pubsub.topic: knative-monitoring
    prow.k8s.io/pubsub.runID: ci-knative-cleanup
  agent: kubernetes
  decorate: true
  cluster: "build-knative"
  decoration_config:
    timeout: 21600000000000
  extra_refs:
  - org: knative
    repo: test-infra
    base_ref: master
  spec:
    containers:
    - image: gcr.io/knative-tests/test-infra/prow-tests-go112:stable
      imagePullPolicy: Always
      command:
      - "go"
      args:
      - "run"
      - "./tools/cleanup/cleanup.go"
      - "--project-resource-yaml=config/prow/boskos_resources.yaml"
      - "--days-to-keep-images=30"
      - "--hours-to-keep-clusters=24"
      - "--service-account=/etc/test-account/service-account.json"
      volumeMounts:
      - name: test-account
        mountPath: /etc/test-account
        readOnly: true
    volumes:
    - name: test-account
      secret:
        secretName: test-account
- cron: "0 12 * * *"
  name: ci-knative-flakes-reporter
  labels:
    prow.k8s.io/pubsub.project: knative-tests
    prow.k8s.io/pubsub.topic: knative-monitoring
    prow.k8s.io/pubsub.runID: ci-knative-flakes-reporter
  agent: kubernetes
  decorate: true
  cluster: "build-knative"
  extra_refs:
  - org: knative
    repo: test-infra
    base_ref: master
  spec:
    containers:
    - image: gcr.io/knative-tests/test-infra/flaky-test-reporter:latest
      imagePullPolicy: Always
      command:
      - "/flaky-test-reporter"
      args:
      - "--service-account=/etc/test-account/service-account.json"
      - "--github-account=/etc/flaky-test-reporter-github-token/token"
      - "--slack-account=/etc/flaky-test-reporter-slack-token/token"
      volumeMounts:
      - name: test-account
        mountPath: /etc/test-account
        readOnly: true
      - name: flaky-test-reporter-github-token
        mountPath: /etc/flaky-test-reporter-github-token
        readOnly: true
      - name: flaky-test-reporter-slack-token
        mountPath: /etc/flaky-test-reporter-slack-token
        readOnly: true
    volumes:
    - name: test-account
      secret:
        secretName: test-account
    - name: flaky-test-reporter-github-token
      secret:
        secretName: flaky-test-reporter-github-token
    - name: flaky-test-reporter-slack-token
      secret:
        secretName: flaky-test-reporter-slack-token
- cron: "0 * * * *"
  name: ci-knative-flakes-resultsrecorder
  labels:
    prow.k8s.io/pubsub.project: knative-tests
    prow.k8s.io/pubsub.topic: knative-monitoring
    prow.k8s.io/pubsub.runID: ci-knative-flakes-reporter
  agent: kubernetes
  decorate: true
  cluster: "build-knative"
  extra_refs:
  - org: knative
    repo: test-infra
    base_ref: master
  spec:
    containers:
    - image: gcr.io/knative-tests/test-infra/flaky-test-reporter:latest
      imagePullPolicy: Always
      command:
      - "/flaky-test-reporter"
      args:
      - "--service-account=/etc/test-account/service-account.json"
      - "--skip-report"
      - "--build-count=20"
      volumeMounts:
      - name: test-account
        mountPath: /etc/test-account
        readOnly: true
      - name: flaky-test-reporter-github-token
        mountPath: /etc/flaky-test-reporter-github-token
        readOnly: true
      - name: flaky-test-reporter-slack-token
        mountPath: /etc/flaky-test-reporter-slack-token
        readOnly: true
    volumes:
    - name: test-account
      secret:
        secretName: test-account
    - name: flaky-test-reporter-github-token
      secret:
        secretName: flaky-test-reporter-github-token
    - name: flaky-test-reporter-slack-token
      secret:
        secretName: flaky-test-reporter-slack-token
- cron: "0 20 * * 1"
  name: ci-knative-prow-auto-bumper
  agent: kubernetes
  decorate: true
  cluster: "build-knative"
  extra_refs:
  - org: knative
    repo: test-infra
    base_ref: master
  spec:
    containers:
    - image: gcr.io/knative-tests/test-infra/prow-auto-bumper:latest
      imagePullPolicy: Always
      command:
      - "/prow-auto-bumper"
      args:
      - "--github-account=/etc/prow-auto-bumper-github-token/token"
      - "--git-userid=knative-prow-updater-robot"
      - "--git-username='Knative Prow Updater Robot'"
      - "--git-email=knative-prow-updater-robot@google.com"
      volumeMounts:
      - name: test-account
        mountPath: /etc/test-account
        readOnly: true
      - name: prow-auto-bumper-github-token
        mountPath: /etc/prow-auto-bumper-github-token
        readOnly: true
      - name: prow-updater-robot-ssh-key
        mountPath: /root/.ssh
        readOnly: true
    volumes:
    - name: test-account
      secret:
        secretName: test-account
    - name: prow-auto-bumper-github-token
      secret:
        secretName: prow-auto-bumper-github-token
    - name: prow-updater-robot-ssh-key
      secret:
        secretName: prow-updater-robot-ssh-key
        defaultMode: 0400

postsubmits:
  knative/test-infra:
  - name: post-knative-prow-config-updater
    agent: kubernetes
    decorate: true
    max_concurrency: 1
    cluster: "prow-trusted"
    run_if_changed: "^(config/(prow|prow-staging)/(cluster|core|jobs|boskos|testgrid)/.*.yaml)|(tools/config-generator/templates/(prow|prow-staging)/.*.yaml)$"
    spec:
      containers:
      - image: gcr.io/knative-tests/test-infra/prow-config-updater:latest
        imagePullPolicy: Always
        command:
        - "/prow-config-updater"
        args:
        - "--github-token-file=/etc/prow-robot-github-token/token"
        - "--github-userid=knative-prow-robot"
        - "--git-username='Knative Prow Robot'"
        - "--git-email=adrcunha+knative-prow-robot@google.com"
        - "--comment-github-token-file=/etc/prow-updater-robot-github-token/token"
        volumeMounts:
        - name: test-account
          mountPath: /etc/test-account
          readOnly: true
        - name: prow-robot-github-token
          mountPath: /etc/prow-robot-github-token
          readOnly: true
        - name: prow-updater-robot-github-token
          mountPath: /etc/prow-updater-robot-github-token
          readOnly: true
        - name: prow-robot-ssh-key
          mountPath: /root/.ssh
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/test-account/service-account.json
      volumes:
      - name: test-account
        secret:
          secretName: test-account
      - name: prow-robot-github-token
        secret:
          secretName: prow-robot-github-token
      - name: prow-updater-robot-github-token
        secret:
          secretName: prow-updater-robot-github-token
      - name: prow-robot-ssh-key
        secret:
          secretName: prow-robot-ssh-key
          defaultMode: 0400
