apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    name: in-cluster
  project: default
  source:
    helm:
      releaseName: grafana
      valueFiles:
      - values.yaml
    path: prow/cluster/monitoring/chart
    repoURL: https://github.com/knative/infra
    targetRevision: main
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
