apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  labels:
    app.kubernetes.io/name: external-secrets
  name: external-secrets
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
  endpoints:
  - port: metrics
    interval: 30s
