# DON'T FORGET TO COMPLETE THE WORKLOAD IDENTITY CONFIGURATION.
kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    iam.gke.io/gcp-service-account: prow-pod-utils@knative-tests.iam.gserviceaccount.com
  name: default
  namespace: test-pods
---
kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    iam.gke.io/gcp-service-account: gsuite-groups-manager@knative-tests.iam.gserviceaccount.com
  name: gsuite-groups-manager
  namespace: test-pods
---
apiVersion: v1
kind: ServiceAccount
metadata:
annotations:
  iam.gke.io/gcp-service-account: prow-deployer@knative-tests.iam.gserviceaccount.com
name: prow-deployer
namespace: test-pods
